name: build and test feature branch
on:
    push:
        branches:
            - feature/*

jobs:
    build-feature:
        runs-on: ubuntu-latest
        
        steps: 
            - name: pull and checkout from git repository
              uses: actions/checkout@v3
              run: | 
                    echo "hola mundo"

            - name: Set up Java 17
              uses: action/setup-java@v3 
              with:
                java-version: '17'
                distribution: 'temurin'
                
            - name: build with Maven
              run: |
                    mvn clean install
                    echo "build with maven"