name: build and test feature branch
on:
    push:
        branches:
            - feature/*

jobs:
    build-feature:
        runs-on: ubuntu-latest
        
        steps: 
            - name: pull and checkout from git repository
              uses: actions/checkout@v3
                

            - name: Set up Java 17
              uses: actions/setup-java@v3 
              with:
                java-version: '17'
                distribution: 'temurin'
                
            - name: Build with Maven
              run: |
                    mvn -B package --file pom.xml     mvn clean install
                    echo "build with maven"